# Generated by Django 4.2.1 on 2023-07-25 04:51

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Document",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                ("document", models.FileField(upload_to="documents/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user", models.CharField(max_length=100)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                ("keywords", models.CharField(max_length=100)),
                (
                    "number",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(500),
                        ]
                    ),
                ),
                ("ja", models.BooleanField()),
                (
                    "choices",
                    models.CharField(
                        choices=[
                            ("1", "ヒット率"),
                            ("5", "発行日[新しい順]"),
                            ("6", "発行日[古い順]"),
                            ("2", "公開日[新しい順]"),
                            ("3", "公開日[古い順]"),
                            ("4", "資料名順"),
                        ],
                        default=("5", "発行日[新しい順]"),
                        max_length=100,
                    ),
                ),
            ],
        ),
    ]
