# Generated by Django 4.2.1 on 2023-06-06 12:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("pls", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="paper",
            name="date",
            field=models.DateTimeField(default=django.utils.timezone.localtime),
        ),
    ]
