# Generated by Django 4.2.1 on 2023-06-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pls", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Paper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("keywords", models.CharField(max_length=100)),
                ("number", models.IntegerField()),
                ("ja", models.BooleanField()),
                ("chices", models.CharField(max_length=100)),
            ],
        ),
    ]
