# Generated by Django 4.2.1 on 2023-06-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pls", "0002_paper"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paper",
            old_name="chices",
            new_name="choices",
        ),
        migrations.AlterField(
            model_name="paper",
            name="ja",
            field=models.IntegerField(),
        ),
    ]
